#!/usr/bin/env python3
"""
WordPress AI 寫文工具 — wordpress-poster skill（Claude skill 模式）

此腳本只負責「把內容發布到 WordPress」。
文章生成由 Claude（對話環境）負責，不需要 ANTHROPIC_API_KEY。

工作流程：
    1. 你在對話中告訴 Claude 主題與要求
    2. Claude 生成 title / content / excerpt
    3. 此腳本接收生成的內容並發布至 WordPress

Requires: httpx, python-dotenv

Usage:
    # 從 JSON 字串發布（由 Claude 在對話中呼叫）
    uv run scripts/wp_ai_writer.py publish '{"title":"...","content":"..."}'

    # 從 JSON 檔案發布
    uv run scripts/wp_ai_writer.py publish-file generated.json

    # 互動模式：貼上 JSON 後確認發布
    uv run scripts/wp_ai_writer.py interactive

JSON 格式：
{
  "title":   "文章標題",
  "content": "<h2>小標</h2><p>HTML 內文...</p>",
  "excerpt": "文章摘要（選填）",
  "status":  "draft",        // 選填，預設 draft
  "categories": [1, 2],      // 選填
  "tags": [3, 4]             // 選填
}
"""
import base64
import json
import os
import sys
import httpx
from dotenv import load_dotenv

load_dotenv()

WP_URL         = os.getenv("WP_URL", "").rstrip("/")
USERNAME       = os.getenv("WP_USERNAME", "")
APP_PASSWORD   = os.getenv("WP_APP_PASSWORD", "")
DEFAULT_STATUS = os.getenv("WP_AI_DEFAULT_STATUS", "draft")
DEFAULT_CAT    = int(os.getenv("WP_AI_DEFAULT_CATEGORY", "0") or "0")


def _auth_headers() -> dict:
    token = base64.b64encode(f"{USERNAME}:{APP_PASSWORD}".encode()).decode()
    return {"Authorization": f"Basic {token}", "Content-Type": "application/json"}


def publish_generated(
    title: str,
    content: str,
    excerpt: str = "",
    status: str = DEFAULT_STATUS,
    categories: list[int] | None = None,
    tags: list[int] | None = None,
) -> dict:
    """
    Publish Claude-generated content to WordPress.
    Call this function after Claude has produced the article text.

    Args:
        title:      Article title (generated by Claude).
        content:    Full HTML content (generated by Claude).
        excerpt:    Short summary (generated by Claude, optional).
        status:     WordPress post status: draft | publish | pending | private.
        categories: List of category IDs.
        tags:       List of tag IDs.

    Returns:
        WordPress post object (includes 'id', 'link', 'status').

    Example:
        post = publish_generated(
            title="CAR-T 細胞療法的最新進展",
            content="<h2>背景</h2><p>...</p>",
            excerpt="本文介紹 CAR-T 療法...",
            status="draft",
        )
        print(post["link"])
    """
    payload: dict = {
        "title":   title,
        "content": content,
        "status":  status,
    }
    if excerpt:
        payload["excerpt"] = excerpt

    cats = categories or ([DEFAULT_CAT] if DEFAULT_CAT else [])
    if cats:
        payload["categories"] = cats
    if tags:
        payload["tags"] = tags

    resp = httpx.post(
        f"{WP_URL}/wp-json/wp/v2/posts",
        json=payload, headers=_auth_headers(), timeout=30,
    )
    resp.raise_for_status()
    return resp.json()


def publish_from_dict(data: dict) -> dict:
    """Convenience wrapper: publish from a dict (Claude's JSON output)."""
    return publish_generated(
        title=data["title"],
        content=data["content"],
        excerpt=data.get("excerpt", ""),
        status=data.get("status", DEFAULT_STATUS),
        categories=data.get("categories"),
        tags=data.get("tags"),
    )


# ── CLI ───────────────────────────────────────────────────────
if __name__ == "__main__":
    if not all([WP_URL, USERNAME, APP_PASSWORD]):
        print("❌ 請先設定 .env：WP_URL, WP_USERNAME, WP_APP_PASSWORD")
        sys.exit(1)

    action = sys.argv[1] if len(sys.argv) > 1 else "help"

    if action == "publish":
        # uv run scripts/wp_ai_writer.py publish '{"title":"...","content":"..."}'
        raw = sys.argv[2]
        data = json.loads(raw)
        post = publish_from_dict(data)
        print(f"✅ 已發布 ID={post['id']}  狀態={post['status']}")
        print(f"   連結: {post['link']}")

    elif action == "publish-file":
        # uv run scripts/wp_ai_writer.py publish-file generated.json
        path = sys.argv[2]
        with open(path, encoding="utf-8") as f:
            data = json.load(f)
        records = data if isinstance(data, list) else [data]
        for i, record in enumerate(records, 1):
            post = publish_from_dict(record)
            print(f"[{i}/{len(records)}] ✅ ID={post['id']}  {post['link']}")

    elif action == "interactive":
        print("請貼上 Claude 生成的 JSON 內容（貼完後按 Enter 兩次）：")
        lines = []
        while True:
            line = input()
            if line == "" and lines:
                break
            lines.append(line)
        data = json.loads("\n".join(lines))
        records = data if isinstance(data, list) else [data]
        print(f"\n準備發布 {len(records)} 篇文章：")
        for r in records:
            print(f"  - {r['title']}  (status={r.get('status', DEFAULT_STATUS)})")
        confirm = input("\n確認發布？[y/N] ").strip().lower()
        if confirm == "y":
            for i, record in enumerate(records, 1):
                post = publish_from_dict(record)
                print(f"[{i}] ✅ ID={post['id']}  {post['link']}")
        else:
            print("已取消。")

    else:
        print(__doc__)
